### PR TITLE
Deprecate GarlandTool

### PR DESCRIPTION
**Pull request by NukoOoOoOoO**
### Changes

- Removed GarlandTool, now using data from excel sheets instead
- Made selling price tooltip follow game language
- Made vendor window always auto-resize and limited the height to half of the screen height
- Fixed some minor issues 

### Notes: 

1. Only tested this on Chinese client, and I don't have global client so I can't really help with that.
2. I heavily changed your code format, let me know if I need to change it back :^)
~~3. Some items like ~~``Paragon's Gown``, ``Makai Priestess's jerkin``,~~  ``Elemental Armor/Weapon``, ~~``Astral Nodule``~~ are not searchable~~

### CODE REVIEW

**Comment by electr0sheep** [comment]
I've been wanting to look into this because surely there must be a way to not go through Garland Tools, but you beat me to it! Would you mind if I target a new branch so I can look into a few issues? Specifically, the following items have the context menu, but nothing happens when you click.

1. Voidrake Seeds
2. Elemental Armor +1
3. Astral Nodule

I want to make sure GC seal items work properly, and that items that cost multiple "currencies" work as well, which I just added support for yesterday.

**Comment by NukoOoOoOoO** [comment]
> Would you mind if I target a new branch so I can look into a few issues?

No problem at all.

> Specifically, the following items have the context menu, but nothing happens when you click.

I am aware of that and working on a fix. ``Voidrake Seeds`` should now work as expected, but ``Elemental Armor/Weapon`` and ``Astral Nodule`` don't, because the SpecialShop row that contains their ids don't get called at anywhere, so currently the only way to address that issue would be hardcoding. Sadly I haven't unlocked Eureka content yet so I can't do anything about ``Elemental Armor/Weapon``.

**Comment by electr0sheep** [comment]
I use the Item Search plugin https://github.com/Caraxi/ItemSearchPlugin so I can test the plugin on whatever items I want. I do appreciate the work though, these network requests suck, especially when you can make no network requests lol

**Comment by NukoOoOoOoO** [comment]
So I just used ItemSearchPlugin to search items, and the plugin can get most of the items that are sold by npcs, except Permits

**Comment by NukoOoOoOoO** [comment]
Now elemental armors & weapons etc. are searchable, also fixed some minor issues

**Comment by electr0sheep** [comment]
Nice, thanks for doing this Nuko. I'll check out your branch and hopefully get it merged when I have some free time.

**Review by electr0sheep — APPROVED** [review]
Thanks for doing this! I'm hoping to have some time to test here in the next few days.

**Pull request merged**
