### PR TITLE
Chat2 and some optimizations

### PR DESCRIPTION
**Pull request by Nukoooo**
## What's changed:
- Added Chat 2 support
- Optimized ``BuildNpcLocation``
    - It now get territories from ``Aetheryte`` sheet instead of looping through the entire ``TerritoryType`` sheet, this cuts about ~2.5 seconds compared to the original method.
    - To get event npcs in ``Eureka``, ``Bozja`` and ``Gathering``(e.g OceanFishing), it now filters ``TerritoryType`` sheet with ``ContentFinderCondition.ContentType``
    - In ``ParseLgbFile``, now we only get event npcs that actually contain data we need like ``GilShop``, ``SpecialShop``, this drastically reduces the load time, which cuts about ~14 seconds: image

I only tested with ``API8`` dalamud fork and the game is patch 6.45, and it seems to work fine.

## TODO:

- [x] Clean up some code
- [x] Change code style(maybe?) @electr0sheep 
    - Use ``var`` instead of explicit type?
    - Use file-scoped namespace. [doc](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-10.0/file-scoped-namespaces)
- [x] Split ``AddItems`` and ``BuildNpcLocation`` into other files. Edit: ``BuildNpcLocation`` wasn't necessary

### CODE REVIEW

**Comment by electr0sheep** [comment]
This all looks good to me.

I'm fine with using var instead of explicit type. Is there a codestyle doc that we can commit so that vs will stop complaining about not using explicit type? Using file scoped namespaces is also fine by me.

I want to build this and test it before approving, but other than that, looks like some good stuff. Thanks for all the work!

**Comment by electr0sheep** [comment]
Seems like everything works to me.

**Review by electr0sheep — APPROVED** [review]

**Comment by Nukoooo** [comment]
Changed a few options in ``.editconfig``, should be good now

**Comment by Nukoooo** [comment]
I guess it's good to merge now :^)

**Comment by electr0sheep** [comment]
I think it may actually be broken if chat2 is not enabled.
```
17:56:45.832 ERR | [LOCALPLUGIN] Error while loading Item Vendor Location
17:56:45.832 ERR | System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
17:56:45.832 ERR |  ---> Dalamud.Plugin.Ipc.Exceptions.IpcNotReadyError: IPC method ChatTwo.Register was not registered yet
17:56:45.832 ERR |    at Dalamud.Plugin.Ipc.Internal.CallGateChannel.InvokeFunc[TRet](Object[] args) in C:\goatsoft\companysecrets\dalamud\Plugin\Ipc\Internal\CallGateChannel.cs:line 141
17:56:45.832 ERR |    at ItemVendorLocation.Ipc.RegisterIpc() in C:\Users\mkdeg\Desktop\ItemVendorLocation\ItemVendorLocation\Ipc.cs:line 53
17:56:45.832 ERR |    at ItemVendorLocation.Ipc.Enable() in C:\Users\mkdeg\Desktop\ItemVendorLocation\ItemVendorLocation\Ipc.cs:line 44
17:56:45.832 ERR |    at ItemVendorLocation.EntryPoint..ctor(DalamudPluginInterface pi) in C:\Users\mkdeg\Desktop\ItemVendorLocation\ItemVendorLocation\EntryPoint.cs:line 87
17:56:45.832 ERR |    at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
17:56:45.832 ERR |    at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
17:56:45.832 ERR |    --- End of inner exception stack trace ---
17:56:45.832 ERR |    at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
17:56:45.832 ERR |    at System.Reflection.RuntimeConstructorInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
17:56:45.832 ERR |    at Dalamud.IoC.Internal.ServiceContainer.CreateAsync(Type objectType, Object[] scopedObjects, IServiceScope scope) in C:\goatsoft\companysecrets\dalamud\IoC\Internal\ServiceContainer.cs:line 146
17:56:45.832 ERR |    at Dalamud.Plugin.Internal.Types.LocalPlugin.LoadAsync(PluginLoadReason reason, Boolean reloading) in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\Types\LocalPlugin.cs:line 451
17:56:45.833 ERR | [PLUGINW] Plugin installer threw an unexpected error
17:56:45.833 ERR | System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
17:56:45.833 ERR |  ---> Dalamud.Plugin.Ipc.Exceptions.IpcNotReadyError: IPC method ChatTwo.Register was not registered yet
17:56:45.833 ERR |    at Dalamud.Plugin.Ipc.Internal.CallGateChannel.InvokeFunc[TRet](Object[] args) in C:\goatsoft\companysecrets\dalamud\Plugin\Ipc\Internal\CallGateChannel.cs:line 141
17:56:45.833 ERR |    at ItemVendorLocation.Ipc.RegisterIpc() in C:\Users\mkdeg\Desktop\ItemVendorLocation\ItemVendorLocation\Ipc.cs:line 53
17:56:45.833 ERR |    at ItemVendorLocation.Ipc.Enable() in C:\Users\mkdeg\Desktop\ItemVendorLocation\ItemVendorLocation\Ipc.cs:line 44
17:56:45.833 ERR |    at ItemVendorLocation.EntryPoint..ctor(DalamudPluginInterface pi) in C:\Users\mkdeg\Desktop\ItemVendorLocation\ItemVendorLocation\EntryPoint.cs:line 87
17:56:45.833 ERR |    at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
17:56:45.833 ERR |    at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
17:56:45.833 ERR |    --- End of inner exception stack trace ---
17:56:45.833 ERR |    at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
17:56:45.833 ERR |    at System.Reflection.RuntimeConstructorInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
17:56:45.833 ERR |    at Dalamud.IoC.Internal.ServiceContainer.CreateAsync(Type objectType, Object[] scopedObjects, IServiceScope scope) in C:\goatsoft\companysecrets\dalamud\IoC\Internal\ServiceContainer.cs:line 146
17:56:45.833 ERR |    at Dalamud.Plugin.Internal.Types.LocalPlugin.LoadAsync(PluginLoadReason reason, Boolean reloading) in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\Types\LocalPlugin.cs:line 451
17:56:45.833 ERR |    at Dalamud.Interface.Internal.Windows.PluginInstaller.PluginInstallerWindow.<>c__DisplayClass102_3.<<DrawPluginControlButton>g__Enabler|10>d.MoveNext() in C:\goatsoft\companysecrets\dalamud\Interface\Internal\Windows\PluginInstaller\PluginInstallerWindow.cs:line 2695
```

**Comment by Nukoooo** [comment]
Oops! Forgot to test it without chat2.. I will push a fix later

**Pull request merged**
